name: CI

on:
  push:
    branches: "**"
    pull_request:

jobs:
  build:
    name: CI on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13

    steps:
      - run: swift --version
      - uses: actions/checkout@v3

      - name: test
        run: swift test

      - name: build for release
        run: swift build -c release
